### ISSUE TITLE
Progress animation and display

### ISSUE THREAD

**Issue by flamencoflsh** [iqnivek/react-circular-progressbar#13]
I currently have two problems with the circular progress path:

1)  It is displaying as a full circle no matter what percentage is set.  For example, with this:

         <CircularProgressbar percentage={60.2} initialAnimation={true}/>

A full circle is displayed rather than just 60.2% even though the text does display as 60.2%.

2) There is no initial animation on refresh even though it is set to true.

Can you advise, @iqnivek ?

Thanks.

**Comment by iqnivek** [comment]
I can't reproduce the "full circle" issue - I'm guessing your full circle issue is due to whatever custom styling you're using. If .CircularProgressbar-trail is the same color as .CircularProgressbar-path, for instance, it'd look like a full circle is displayed for all percentages. Make sure the stroke colors are different for those two CSS classes - the [example CSS](https://github.com/iqnivek/react-circular-progressbar/blob/master/src/styles.css) should give you an idea of it.

The initialAnimation issue might also be caused by your styling - you need a CSS transition in order to have it work. Again, see the example CSS. If you're still having problems, please send your HTML/CSS/JS setup so I can take a look at what's wrong. Thanks.

**Comment by shrishail091** [comment]
Hi , 
For animation, issue use the below code in your css file.

  .CircularProgressbar .CircularProgressbar-path {
    stroke-linecap: round;
    transition: stroke-dashoffset 0.5s ease 0s;
  }
