### ISSUE TITLE
Vertical align of percentage text in IE 10 +

### ISSUE THREAD

**Issue by saharaquant** [iqnivek/react-circular-progressbar#35]
So IE doesn't support dominant-baseline/alignment-baseline: central/middle css properties.
How do you suggest to vertical align the precentage text inside the circle?
(In IE 10 it's aligned to the top)

**Comment by iqnivek** [comment]
Yeah, this seems troublesome to do without a workaround hack at this point. I'd much rather not build browser/feature detection into the component, but there doesn't seem to be a CSS-only solution either, which sucks, because that means you may have to do DOM manipulation outside the react lifecycle like this:

```
document.querySelector('.CircularProgressbar-text').setAttribute('dy', '0.3em')
```

You could wrap CircularProgressbar in a custom component and execute the setAttribute call in componentDidMount using refs instead of querySelector, or something like that. Haven't tested this in IE, but it's my best guess if you need an IE workaround.

**Comment by iqnivek** [comment]
Closing because this hasn't gotten an update in a while, but if you're still having a problem with this feel free to reopen!

**Comment by redaxmedia** [comment]
Here comes some really ugly workarround for IE:

```
  componentDidUpdate: () => {
    if (window.navigator.userAgent.indexOf('MSIE') === -1) {
      [].forEach.call(document.querySelectorAll('.CircularProgressbar-text'), element => {
        element.setAttribute('dy', '0.3em');
      });
    }
  }
```
