### ISSUE TITLE
Circular Progressbar Text color is not setting properly

### ISSUE THREAD

**Issue by boriskogan81** [iqnivek/react-circular-progressbar#43]
I'm attempting to set the color to #606A7B via CSS, like this: 

```
.CircularProgressbar .CircularProgressbar-text {
	color: '#606A7B';
}
```

When I inspect the element, I see that it has the proper color set, nothing is overriding it, but in the browser, the text is still black. Am I doing something wrong?

**Comment by iqnivek** [comment]
Because `<text>` is an svg element, you should use `fill` instead of `color`. Take a look at the default stylesheet to see how to get started, and you can modify from there: https://github.com/iqnivek/react-circular-progressbar/blob/master/src/styles.css#L27

**Comment by boriskogan81** [comment]
I don't mean to be a pain in the ass, but fill doesn't work either-something is overriding it, even when I mark it as !important.

**Comment by iqnivek** [comment]
Can you verify that this example works for you and has colored text? https://codesandbox.io/s/vymm4oln6y

If it does work, then take a look at what you might be configuring differently. If the color's being overridden, you should be able to see what's overriding it in developer tools. Otherwise, please post the code you're using.

**Comment by iqnivek** [comment]
So codesandbox.io doesn't work for you at all? What browser version / OS are you on?

**Comment by boriskogan81** [comment]
Now it works, and yes, text is colored.
