### ISSUE TITLE
Props for semi-circle progressbar

### ISSUE THREAD

**Issue by var-bp** [iqnivek/react-circular-progressbar#46]
Hi, is there any props to achieve something like this?
<img width="162" alt="semi-circle" src="https://user-images.githubusercontent.com/16168934/36089822-63d3d414-0fe6-11e8-9220-05155dda2475.png">

**Comment by Offirmo** [comment]
By combining rotation https://github.com/iqnivek/react-circular-progressbar/issues/38 + multiplying the percentage by ~0.6 you should be able to achieve this.

**Comment by iqnivek** [comment]
hmm, yeah you can certainly rotate the progressbar, but I don't think you can actually scale the whole bar just by multiplying by a fraction, because that would just scale the colored path, not the full gray trail - you'd need some other trickery to achieve the partial arc. Also, there's no built-in way to implement the white separators between each 10% segment. This use case is complex enough that you may want to find an alternative, or perhaps look at the source and roll your own. Sorry I can't be of more help!

**Comment by iqnivek** [comment]
Just as a followup - adding the white separators is possible by overlaying content, and I have a demo up at https://codesandbox.io/s/ov22pywr19.

Reducing the progressbar to a semi-circle is still not implemented yet, but I may get to it as part of PR #49.

**Comment by kevinsqi** [comment]
@var-bp @Offirmo 

Making the progressbar only arc ~60% of the full diameter is now possible in v1.2.1 with `props.circleRatio`! See more details here: https://github.com/kevinsqi/react-circular-progressbar/issues/49#issuecomment-487448279
