### ISSUE TITLE
Pie display instead of border circle

### ISSUE THREAD

**Issue by Offirmo** [iqnivek/react-circular-progressbar#47]
For very small indicators, a pie display would be more readable, ex. https://www.theverge.com/2017/5/19/15664348/things-3-review-ios-mac-productivity (1st picture)

Is that possible ?

**Comment by iqnivek** [comment]
Just tried it out and a basic pie display is possible by setting strokeWidth to 50, and tweaking the CSS to be

```
.CircularProgressbar-path { stroke-linecap: butt; }
.CircularProgressbar-trail { stroke: transparent; }
```

Here's an example: https://codesandbox.io/s/7mjzyq9x9x

<img width="400" alt="screen shot 2018-02-27 at 9 04 53 pm" src="https://user-images.githubusercontent.com/396006/36770910-fec8e5a0-1c01-11e8-88e7-5ee71bdde3c3.png">

**Comment by Offirmo** [comment]
Nice but the trail was pretty nice before ;)
![screen shot 2018-03-01 at 15 41 52](https://user-images.githubusercontent.com/603503/36827342-208b5540-1d67-11e8-8bf8-e3eadbb882bc.png)

P.S. your lib is amazing.

**Comment by iqnivek** [comment]
Thanks, appreciate the kind words!

You can get partway to what you're looking for by setting the background color, e.g.: https://codesandbox.io/s/v81xrrq7k0

However, I don't think there's any built-in way to add the extra border you have there, and I think that's outside the scope of the component itself. You could do it by by overlaying the progressbar on top of some background element that's shaped like a circle though (e.g. an svg circle or a div with 50% border radius), using absolute positioning as demonstrated with https://github.com/iqnivek/react-circular-progressbar/issues/32#issuecomment-369129732, but changing the order of the children so the progressbar is in the foreground instead of background.

Hope this helps.
