### ISSUE TITLE
How to set ending point

### ISSUE THREAD

**Issue by gemaaa26** [iqnivek/react-circular-progressbar#53]
Hello,
How if we want to set the end point? currently only set to 100, I want to set the end point to 10.

thanks, great component.

**Comment by iqnivek** [comment]
Hi gemaaa!

I'm not exactly sure what you mean by "set the end point", but I'm guessing this means changing the scale of the `percentage` prop so it ranges from 0-10 instead of 0-100?

If so, you'd need to scale the percentage and also tweak textForPercentage. See an example here: https://codesandbox.io/s/6z64omwv3n

<img width="880" alt="screen shot 2018-04-26 at 10 12 45 pm" src="https://user-images.githubusercontent.com/396006/39345734-f8a5cb46-499e-11e8-8063-c0782c759336.png">

Does that address your question?

**Comment by gemaaa26** [comment]
yes, I mean the scale the percentage, thanks for explaining that's I looking for. Great!

**Comment by iqnivek** [comment]
Glad I could answer your question!
