### ISSUE TITLE
Set state to change text fill & path stroke colour when percentage >= 30

### ISSUE THREAD

**Issue by andy3wood** [iqnivek/react-circular-progressbar#75]
I would like to update this state during the animation, so start on green and changes to red as soon as the percentage value is greater than 30 I have tried this:
.CircularProgressbar-text {
  fill: ${props => (props.percentage >= '30' ? 'green' : 'red')};
}
but will only update when i toggle the knob (using storybook) I cannot get it to work on page load.

many thanks

**Comment by iqnivek** [comment]
The syntax you posted doesn't look quite right for either CSS or JS styling approaches. I'd expect it to look something like:

```jsx
const percentage = props.percentage;

<CircularProgressbar
  percentage={percentage}
  styles={{
    text: {
      fill: percentage >= 30 ? 'green' : 'red'
    }
  }}
/>
```

If this doesn't help, can you post your code or a codesandbox demonstrating the issue?

**Comment by andy3wood** [comment]
Hey thats OK unfortunately both ways achieve the same anyway, I would like the colour to change as the progress bar passes '30' rather than decide the colour before load, if this makes sense? So before 30 colours should be green as soon as progress and countup over 30 colours change to red
https://codesandbox.io/s/1rrlq6wrnj

**Comment by iqnivek** [comment]
Ah, I see the issue. Basically, your example is using CSS transitions, which are unaware of the JS-specified styles (which encode the logic of "if percentage is >30, use this color"). So if you set percentage=0 and percentage=60, React will apply the color changes instantaneously, instead of when the percentage in the CSS animation passes 30%.

If you want the styles to be applied "in between", you'll need to tween `props.percentage` directly instead of relying on CSS animation. You can see how to do this here: https://codesandbox.io/s/3r6p9q361p

I can see why this is confusing, but it is a bit of a limitation of using CSS transitions which aren't aware of JS state. Does this help?

**Comment by andy3wood** [comment]
Hey @iqnivek thanks for recommending spring it looks super interesting, not sure how i'll get around nested returns considering but i will give it a go, thank you!

**Comment by iqnivek** [comment]
Cool! There may be lighter weight alternatives to react-spring since the functionality used is fairly simple - all you need is an HOC or renderProp component that tweens percentage from one value to another (I'm not sure what alternatives are out there, though). Good luck, and feel free to reopen this if you have any other issues related to this.
