### ISSUE TITLE
Is there a way to nest progressbars?

### ISSUE THREAD

**Issue by smeads** [iqnivek/react-circular-progressbar#8]
I apologize if this is a non conventional way of asking this question, but I really like what you've done and I'm trying to nest one progressbar within the other. Does this functionality exist, and if so could you prompt me on how to do so?

If this functionality doesn't exist it would be a great feature to build out.

Thx.

**Comment by iqnivek** [comment]
hmm, nesting isn't supported by the component, and since that seems like a pretty niche use case I don't think I'd plan to add support for that. However, I suspect that you could use CSS to achieve that effect, by using absolute positioning to overlay progressbars of increasing radii that share the same center point. I haven't tested it so no guarantees, but that's could be a reasonable solution to what you're looking for.
